name: Coverage
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, dev]
jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.20"
      - name: Generate coverage report
        run: make cover
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: coverage.out
          fail_ci_if_error: true
          verbose: true
