name: Build And Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests: 
    name: Test on node ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.20', '1.21']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go environment, version=${{ matrix.go_version }}
        uses: actions/setup-go@v4.1.0
        with: 
          go-version: ${{ matrix.go_version }}
      - name: go test
        run: |
          make test
